"""
itinerary.py — AI-powered visual itinerary generator for Travel Brain.

POST /itinerary/generate
  → Accepts: destination, duration (days), budget, travel_style
  → Returns: structured JSON itinerary with days, activities, costs, affiliate links

The itinerary is generated by Gemini using RAG context from our vector DB.
"""

import json
import logging
import os
import sys
from pathlib import Path
from typing import Optional

from fastapi import APIRouter
from pydantic import BaseModel, Field

sys.path.insert(0, str(Path(__file__).parent.parent.parent))
from travel_brain import config

logger = logging.getLogger(__name__)
router = APIRouter(prefix="/itinerary", tags=["Itinerary"])


# ── Request / Response Schemas ────────────────────────────────────────────────

class ItineraryRequest(BaseModel):
    destination: str = Field(..., description="'bali' or 'dubai'")
    days: int        = Field(default=5, ge=1, le=14, description="Trip duration in days")
    budget: str      = Field(default="mid", description="'budget', 'mid', or 'luxury'")
    travel_style: str = Field(default="explorer", description="'explorer', 'relaxation', 'culture', 'foodie', 'adventure'")
    focus: Optional[str] = Field(default=None, description="Optional specific focus, e.g. 'beaches only' or 'family with kids'")

class Activity(BaseModel):
    time: str
    name: str
    description: str
    location: str
    estimated_cost: str
    tip: Optional[str] = None
    booking_link: Optional[str] = None

class DayPlan(BaseModel):
    day: int
    theme: str
    emoji: str
    activities: list[Activity]
    total_day_budget: str

class ItineraryResponse(BaseModel):
    destination: str
    title: str
    duration_days: int
    budget_level: str
    total_estimated_cost: str
    best_time_to_visit: str
    days: list[DayPlan]
    pro_tips: list[str]
    packing_essentials: list[str]


# ── Affiliate link generators ─────────────────────────────────────────────────

def _booking_link(destination: str, activity_name: str = "") -> str:
    dest_map = {"bali": "bali-bali", "dubai": "dubai-emirate-of-dubai"}
    dest = dest_map.get(destination.lower(), destination)
    return f"https://www.booking.com/region/{dest}.html?aid=travelbrain_hq&label=itinerary"

def _getyourguide_link(destination: str, activity: str) -> str:
    q = activity.replace(" ", "+")
    dest_map = {"bali": "bali", "dubai": "dubai"}
    dest = dest_map.get(destination.lower(), destination)
    return f"https://www.getyourguide.com/{dest}/-l209/?partner_id=travelbrain_hq&q={q}"


# ── Prompt builder ────────────────────────────────────────────────────────────

def _build_prompt(req: ItineraryRequest, context: str) -> str:
    budget_guide = {
        "budget": "under $50/day total — hostels, street food, free attractions",
        "mid":    "$100-200/day — boutique hotels, local restaurants, some paid experiences",
        "luxury": "$300+/day — 5-star resorts, fine dining, private tours",
    }.get(req.budget, "mid-range")

    style_guide = {
        "explorer":   "discovering hidden gems, off-the-beaten-path spots",
        "relaxation": "beach clubs, spas, sunsets, slow mornings",
        "culture":    "temples, museums, local markets, authentic experiences",
        "foodie":     "local warungs, street food, cooking classes, night markets",
        "adventure":  "surfing, trekking, water sports, outdoor activities",
    }.get(req.travel_style, "balanced mix")

    focus_note = f"\nSpecial focus: {req.focus}" if req.focus else ""

    return f"""You are an expert local travel guide for {req.destination.title()}.
Create a detailed {req.days}-day itinerary for someone with {req.budget} budget ({budget_guide}) who loves {style_guide}.{focus_note}

Use this real traveler knowledge from our database:
---
{context}
---

Return ONLY valid JSON matching this exact schema (no markdown, no extra text):
{{
  "destination": "{req.destination}",
  "title": "A catchy, evocative title for this trip (e.g. '7 Days of Hidden Bali')",
  "duration_days": {req.days},
  "budget_level": "{req.budget}",
  "total_estimated_cost": "e.g. '$650 - $900 total'",
  "best_time_to_visit": "e.g. 'April to October (dry season)'",
  "days": [
    {{
      "day": 1,
      "theme": "Short theme name (e.g. 'Arrival & Seminyak Vibes')",
      "emoji": "One relevant emoji",
      "total_day_budget": "e.g. '$85'",
      "activities": [
        {{
          "time": "Morning / Afternoon / Evening",
          "name": "Activity or place name",
          "description": "2-3 sentences of rich, specific, useful description. Include what makes it special, any insider tips.",
          "location": "Specific area/neighborhood",
          "estimated_cost": "e.g. 'Free' or '$15 pp' or '$40/hr'",
          "tip": "Optional insider tip from a local or experienced traveler",
          "booking_link": null
        }}
      ]
    }}
  ],
  "pro_tips": ["3-5 essential tips specific to this trip type and budget"],
  "packing_essentials": ["5-7 items specific to {req.destination} and travel style"]
}}

Rules:
- Be hyper-specific: use real place names, real neighborhoods, real local spots
- For {req.destination.title()}: include places locals actually love, not just tourist traps
- Each day should have 3-4 activities (morning, afternoon, evening + optional night)
- Make costs realistic and specific to {req.budget} budget
- Pro tips must be genuinely useful, not generic advice"""


# ── Main generation endpoint ──────────────────────────────────────────────────

@router.post("/generate", response_model=ItineraryResponse, summary="Generate AI itinerary")
async def generate_itinerary(req: ItineraryRequest):
    """
    Generate a personalized day-by-day travel itinerary using AI + local RAG knowledge.
    Returns structured JSON with activities, costs, tips, and affiliate booking links.
    """
    # Pull relevant context from vector DB
    context = ""
    try:
        from travel_brain.api.query import get_db
        from travel_brain.processing.embedder import embed_texts
        query_text = f"{req.destination} {req.travel_style} {req.budget} travel tips hidden gems itinerary"
        vectors = embed_texts([query_text])
        if vectors:
            db = get_db()
            results = db.query(
                query_embeddings=vectors,
                n_results=12,
                namespace=req.destination.lower(),
            )
            chunks = results.get("documents", [[]])[0]
            context = "\n\n".join(chunks[:10]) if chunks else ""
    except Exception as e:
        logger.warning(f"Could not fetch RAG context: {e}")
        context = f"Expert travel knowledge about {req.destination}"

    # Call Gemini (with retry on rate limit)
    import time
    last_err = None
    for attempt in range(2):
        try:
            from google import genai
            from google.genai import types as gtypes
            client = genai.Client(api_key=config.GEMINI_API_KEY)
            prompt = _build_prompt(req, context)

            response = client.models.generate_content(
                model=os.getenv("GEMINI_MODEL", "gemini-2.5-flash"),
                contents=prompt,
                config=gtypes.GenerateContentConfig(
                    temperature=0.7,
                    max_output_tokens=8192,
                    response_mime_type="application/json",
                ),
            )

            raw = response.text.strip()
            if raw.startswith("```"):
                raw = raw.split("```")[1]
                if raw.startswith("json"):
                    raw = raw[4:]

            itinerary_data = json.loads(raw)

            for day in itinerary_data.get("days", []):
                for act in day.get("activities", []):
                    if act.get("booking_link") is None:
                        name = act.get("name", "")
                        if any(kw in name.lower() for kw in ["tour", "class", "temple", "safari", "surf", "trek", "dive", "cruise"]):
                            act["booking_link"] = _getyourguide_link(req.destination, name)
                        else:
                            act["booking_link"] = None

            return ItineraryResponse(**itinerary_data)

        except Exception as e:
            err_str = str(e)
            if attempt == 0 and ("402" in err_str or "429" in err_str or "RESOURCE_EXHAUSTED" in err_str):
                logger.warning(f"Rate limit on itinerary (attempt {attempt+1}), retrying in 15s: {e}")
                time.sleep(15)
                last_err = e
                continue
            logger.error(f"Itinerary generation failed: {e}", exc_info=True)
            raise

    logger.error(f"Itinerary failed after retry: {last_err}")
    raise last_err
